travis:
  secure:
    BINSTAR_TOKEN: POgKSmM2sKshSG1GFMSbG4+H+PEJABO460DqpheLDjlc8f+a/q6SeEEPb5Db+27zb81b7LQ8s8YadH4Qi8ZTCmiF4CDby2X2Nc080ZkHcNLatqk6bjErnHvQJwEpFx0gLRKfK5KoEX+Zx2KvR+ZoVQiptUthAJO+NoRFW+uouyaHXKN81PIQVFvjgINB8V09czjw8XcClNaylsLA+UaudIH8PSAwBZfaNFp7orjEgk9w3g97ebf/BxFTWUiN5Dm86xZqRTaCapkM3PHVV/mLAQdrxK418PVrBLzdgrFKaJNroXJDRKHO3nzEKT45CT1W+YoE+tejwdQDXA38v7p1LWPDqQUZweSDytl0PX29jHt9j7FyPn5ZNFTLqr94pn1U2kbRUnH0OlB5VfBd4XU+T/fL4hW0Ak+SV+bLY8mjGa8VW0gF6/6ZGwSYlD7fAseke/n+dQ1PHoDON5SVkXeBHZAAfVJbIoHMn6Ax4z3CO24V6fJ8oKgX7/YjeAj20yGSZ3D0mHJsjTJ95ywSPTAiBWO9QA4sWIW6lGPmz7mZafYpAypO0ma3GC2sHI9cl4rcS8Xd4FiKgAc3QjS8yg+Net7tIAZ01Q9Cm26dNTaxJSs6cHNAKVQf6wxeWr3IjtyqDk2GNazHMqz1pySu5OiOEd7EyK/kh5rf+Dz2AKTRlOo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
